const fs = require('fs');
const path = require('path');

const initialCategories = [
  {
    id: 'cat-tilam-toto',
    name: 'Tilam Toto',
    slug: 'tilam-toto',
    description: 'Tilam Toto Asian Polyester Fibre tebal, empuk dan berkualiti tinggi keluaran kilang Tunas Sinar Jaya. Paling laris untuk seisi keluarga.',
    imageUrl: '/images/company/profil-syarikat-cover.jpg',
    displayOrder: 1,
    showInNav: true,
    hasMegaMenu: true,
    badge: 'PALING LARISS',
    isActive: true,
  },
  {
    id: 'cat-tilam-lipat',
    name: 'Tilam Lipat & Bujang',
    slug: 'tilam-lipat',
    description: 'Tilam lipat 3 berzip mudah alih dan tilam bujang asrama yang praktikal, jimat ruang dan tahan lasak.',
    imageUrl: '/images/company/aktiviti-pengilangan.jpg',
    displayOrder: 2,
    showInNav: true,
    hasMegaMenu: false,
    isActive: true,
  },
  {
    id: 'cat-bantal',
    name: 'Bantal & Bantal Peluk',
    slug: 'bantal',
    description: 'Bantal tidur gebu dan bantal peluk isian Asian Polyester Fibre dari Unit Bantal & Tilam KAMAAR.',
    imageUrl: '/images/products/pillow-classic-latex.jpg',
    displayOrder: 3,
    showInNav: true,
    hasMegaMenu: false,
    isActive: true,
  },
  {
    id: 'cat-cadang-comforter',
    name: 'Cadar & Comforter',
    slug: 'cadang-comforter',
    description: 'Set comforter tebal jahitan quilting kemas, cadar tilam toto dan sarung tilam berzip pelbagai corak menarik.',
    imageUrl: '/images/company/profil-syarikat-cover.jpg',
    displayOrder: 4,
    showInNav: true,
    hasMegaMenu: false,
    isActive: true,
  },
  {
    id: 'cat-borong-gudang',
    name: 'Jualan Gudang & Borong',
    slug: 'borong-gudang',
    description: 'Harga kilang terus dari Tasek Gelugor untuk asrama, homestay, tahfiz, kontraktor dan pembeli borong.',
    imageUrl: '/images/company/misi-visi-jualan-gudang.jpg',
    displayOrder: 5,
    showInNav: true,
    hasMegaMenu: false,
    badge: 'HARGA KILANG',
    isActive: true,
  },
  {
    id: 'cat-profil',
    name: 'Profil Syarikat',
    slug: 'profil',
    description: 'Maklumat syarikat Tunas Sinar Jaya Enterprise, carta organisasi, visi misi dan aktiviti pengilangan tekstil.',
    imageUrl: '/images/company/carta-organisasi-kilang.jpg',
    displayOrder: 6,
    showInNav: true,
    hasMegaMenu: false,
    customUrl: '/profil',
    isActive: true,
  },
];

const initialCollections = [
  {
    id: 'col-toto',
    name: 'Koleksi Tilam Toto Paling Laris',
    slug: 'koleksi-toto',
    description: 'Tilam toto tebal isian Asian Polyester Fibre pelbagai corak floral dan moden terus dari kilang.',
    bannerUrl: '/images/company/profil-syarikat-cover.jpg',
    displayOrder: 1,
    isFeatured: true,
  },
  {
    id: 'col-lipat-bujang',
    name: 'Tilam Lipat 3 & Bujang Asrama',
    slug: 'tilam-lipat-asrama',
    description: 'Tilam mudah alih berzip dan tilam bujang tahan lasak untuk kegunaan asrama, homestay & ruang tamu.',
    bannerUrl: '/images/company/aktiviti-pengilangan.jpg',
    displayOrder: 2,
    isFeatured: true,
  },
  {
    id: 'col-bantal-peluk',
    name: 'Bantal Tidur Gebu & Bantal Peluk',
    slug: 'bantal-gebu-kamaar',
    description: 'Isian fiber berkualiti tinggi yang anjal, menyokong kepala dan leher dengan selesa.',
    bannerUrl: '/images/products/pillow-contour-latex.jpg',
    displayOrder: 3,
    isFeatured: true,
  },
  {
    id: 'col-borong-pukal',
    name: 'Pakej Jualan Gudang & Borong',
    slug: 'jualan-gudang-borong',
    description: 'Pakej penjimatan besar untuk pengusaha homestay, asrama sekolah, tahfiz dan jualan gudang.',
    bannerUrl: '/images/company/misi-visi-jualan-gudang.jpg',
    displayOrder: 4,
    isFeatured: true,
  },
];

const initialProducts = [
  {
    id: 'prod-toto-asian-fibre',
    name: 'Tilam Toto Asian Polyester Fibre (Tebal & Gebu)',
    slug: 'tilam-toto-asian-polyester-fibre',
    subtitle: 'Paling Lariss!! Tebal, Gebu & Jahitan Quilting Tahan Lasak',
    description: 'Produk terlaris keluaran Tunas Sinar Jaya Enterprise! Tilam toto tebal dan empuk dengan isian Asian Polyester Fibre bermutu tinggi. Jahitan quilting kemas yang mengunci fiber agar tidak berganjak atau bergumpal. Sesuai untuk tidur santai seisi keluarga di ruang tamu, tilam tambahan untuk tetamu, homestay, atau aktiviti luar.',
    shortDescription: 'Tilam toto paling laris keluaran Tunas Sinar Jaya Enterprise. Tebal, gebu, corak menarik dan tahan lasak.',
    categoryId: 'cat-tilam-toto',
    productType: 'mattress',
    material: 'Asian Polyester Fibre & Fabrik Jahitan Berkualiti',
    firmness: 'Medium Soft',
    firmnessScale: 4,
    thicknessCm: 8,
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Isian 100% Asian Polyester Fibre berkualiti & padat',
      'Jahitan quilting mesin industri kilang sendiri di Tasek Gelugor',
      'Corak menarik pelbagai pilihan (Random Floral Design & Geometrik)',
      'Fabrik sejuk, tidak memerangkap haba, lembut pada kulit',
      'Senang digulung, disimpan, dan dibawa ke mana-mana',
      'Harga terus dari kilang tanpa orang tengah',
    ],
    layers: [
      { number: 1, name: 'Fabrik Luar Corak Bunga / Moden', description: 'Fabrik mikrofiber sejuk, tahan luntur dan lembut bila disentuh.' },
      { number: 2, name: 'Lapisan Quilting Mesin Jahit Industri', description: 'Jahitan corak berlian/ombak yang mengukuhkan struktur tilam toto.' },
      { number: 3, name: 'Teras Asian Polyester Fibre Padat', description: 'Fiber sintetik terpilih yang anjal, gebu dan memberikan keselesaan maksimum.' },
      { number: 4, name: 'Lapisan Bawah Tahan Geseran', description: 'Kain lapik bawah yang tahan lasak dan kemas jahitannya.' },
    ],
    specifications: {
      'Bahan Isian': '100% Asian Polyester Fibre Gred A',
      'Fabrik Luaran': 'Mikrofiber Lembut Sejuk (Corak Bunga & Moden)',
      'Ketebalan': 'Kira-kira 7cm - 10cm (Gebu & Empuk)',
      'Kaedah Jahitan': 'Quilting Mesin Industri Berketumpatan Tinggi',
      'Kebolehbasuhan': 'Boleh dijemur & lap bersih / sarung boleh basuh',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise (Tasek Gelugor, Pulau Pinang)',
    },
    faq: [
      { question: 'Apakah corak tilam toto yang akan saya terima?', answer: 'Kami menyediakan corak menarik (Random Design) berasaskan corak floral bunga dan geometrik yang popular dan kemas. Anda juga boleh nyatakan pilihan warna di bahagian nota pesanan.' },
      { question: 'Bolehkah tilam toto ini digulung untuk disimpan?', answer: 'Ya, tilam toto ini sangat fleksibel dan mudah digulung atau dilipat untuk disimpan di dalam almari atau dibawa dalam kereta.' },
    ],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-toto-single', productId: 'prod-toto-asian-fibre', sku: 'TSJ-TOTO-SGL', sizeName: 'Single (Bujang)', dimensions: '90cm x 190cm x 8cm', priceSen: 5900, compareAtPriceSen: 7900, stockQuantity: 50, leadTimeDays: 1, isActive: true },
      { id: 'var-toto-queen', productId: 'prod-toto-asian-fibre', sku: 'TSJ-TOTO-QEN', sizeName: 'Queen (Standard)', dimensions: '150cm x 190cm x 8cm', priceSen: 8900, compareAtPriceSen: 11900, stockQuantity: 65, leadTimeDays: 1, isActive: true },
      { id: 'var-toto-king', productId: 'prod-toto-asian-fibre', sku: 'TSJ-TOTO-KNG', sizeName: 'King (Besar)', dimensions: '180cm x 190cm x 10cm', priceSen: 11900, compareAtPriceSen: 14900, stockQuantity: 40, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-toto-1', productId: 'prod-toto-asian-fibre', imageUrl: '/images/company/profil-syarikat-cover.jpg', altText: 'Tilam Toto Asian Polyester Fibre Paling Lariss Tunas Sinar Jaya', displayOrder: 1, isPrimary: true },
      { id: 'img-toto-2', productId: 'prod-toto-asian-fibre', imageUrl: '/images/company/aktiviti-pengilangan.jpg', altText: 'Aktiviti jahitan dan stor produk siap tilam toto', displayOrder: 2, isPrimary: false },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-toto-gulung',
    name: 'Tilam Toto Gulung Mudah Alih (Travel & Santai)',
    slug: 'tilam-toto-gulung-mudah-alih',
    subtitle: 'Siap Tali Pengikat • Mudah Gulung & Bawa Berkelah / Homestay',
    description: 'Tilam toto jenis gulung kompak yang dilengkapi tali pengikat khas. Sangat praktikal untuk aktiviti luar, berkelah, asrama sekolah, ataupun tilam santai anak-anak di depan TV.',
    shortDescription: 'Tilam toto gulung mudah alih dengan tali pengikat siap. Praktikal untuk travel dan ruang tamu.',
    categoryId: 'cat-tilam-toto',
    productType: 'mattress',
    material: 'Asian Polyester Fibre Padat',
    firmness: 'Medium',
    firmnessScale: 5,
    thicknessCm: 6,
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Dilengkapi tali pengikat terbina untuk mudah gulung',
      'Ringan dan mudah dibawa masuk bonet kereta',
      'Isian fiber mampat yang tahan lasak',
      'Sesuai untuk camping, homestay, asrama & ruang santai',
    ],
    layers: [
      { number: 1, name: 'Kain Sarung Lembut', description: 'Fabrik kapas mikrofiber yang selesa dan tidak panas.' },
      { number: 2, name: 'Teras Fiber Kompak', description: 'Isian fiber sintetik yang mampat dan tidak mudah penyek.' },
    ],
    specifications: {
      'Bahan': 'Polyester Fibre Padat',
      'Ketebalan': 'Kira-kira 6 cm',
      'Ciri Khas': 'Tali Pengikat Terbina Dalam',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [
      { question: 'Berapakah berat tilam gulung ini?', answer: 'Kira-kira 2kg hingga 3.5kg mengikut saiz, sangat ringan untuk diangkat oleh sesiapa sahaja.' },
    ],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-gulung-sgl', productId: 'prod-toto-gulung', sku: 'TSJ-GULUNG-SGL', sizeName: 'Single (90x180cm)', dimensions: '90cm x 180cm x 6cm', priceSen: 4900, compareAtPriceSen: 6500, stockQuantity: 30, leadTimeDays: 1, isActive: true },
      { id: 'var-gulung-qen', productId: 'prod-toto-gulung', sku: 'TSJ-GULUNG-QEN', sizeName: 'Queen (140x190cm)', dimensions: '140cm x 190cm x 6cm', priceSen: 7900, compareAtPriceSen: 9900, stockQuantity: 25, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-gulung-1', productId: 'prod-toto-gulung', imageUrl: '/images/company/profil-syarikat-cover.jpg', altText: 'Tilam toto gulung mudah alih KAMAAR', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-tilam-lipat-3',
    name: 'Tilam Lipat 3 Berzip Fabrik Tahan Lasak',
    slug: 'tilam-lipat-3-berzip',
    subtitle: 'Sarung Berzip Boleh Buka Cuci • Jimat Ruang & Praktikal',
    description: 'Tilam lipat 3 bahagian yang menjimatkan ruang penyimpanan. Isian busa/fiber mampat yang tahan lasak dan tidak mudah penyek. Sarung berzip mudah ditanggalkan untuk dicuci. Pilihan terbaik untuk rumah sewa, asrama, dan tilam tetamu.',
    shortDescription: 'Tilam lipat 3 bahagian berzip yang boleh dicuci sarungnya. Jimat ruang dan selesa.',
    categoryId: 'cat-tilam-lipat',
    productType: 'mattress',
    material: 'Fiber / Busa Mampat Berketumpatan Tinggi',
    firmness: 'Medium Firm',
    firmnessScale: 6,
    thicknessCm: 7,
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Rekaan 3 lipatan mudah simpan dalam almari atau sudut bilik',
      'Sarung kain tebal dilengkapi zip penuh untuk mudah dicuci',
      'Isian mampat yang menyokong tulang belakang dengan baik',
      'Jahitan piping kemas di Unit Jahitan Tunas Sinar Jaya',
    ],
    layers: [
      { number: 1, name: 'Sarung Berzip Boleh Cuci', description: 'Kain bercorak kemas dengan bukaan zip panjang.' },
      { number: 2, name: 'Teras Busa/Fiber Mampat 3 Bahagian', description: 'Blok isian tahan lasak yang mengekalkan bentuk rata.' },
    ],
    specifications: {
      'Jenis': 'Tilam Lipat 3 Segi Empat',
      'Saiz Buka': 'Single (90cm x 190cm)',
      'Saiz Lipat': '90cm x 63cm x 22cm',
      'Sarung': 'Fabrik Berzip Boleh Dicuci',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [
      { question: 'Bolehkah sarung tilam ini dibasuh mesin?', answer: 'Ya, buka zip dan masukkan sarung ke dalam mesin basuh dengan cucian biasa.' },
    ],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-lipat-2in', productId: 'prod-tilam-lipat-3', sku: 'TSJ-LIPAT-2IN', sizeName: 'Single 2 Inci Tebal', dimensions: '90cm x 190cm x 5cm', priceSen: 6900, compareAtPriceSen: 8900, stockQuantity: 40, leadTimeDays: 1, isActive: true },
      { id: 'var-lipat-3in', productId: 'prod-tilam-lipat-3', sku: 'TSJ-LIPAT-3IN', sizeName: 'Single 3 Inci Extra Tebal', dimensions: '90cm x 190cm x 8cm', priceSen: 8900, compareAtPriceSen: 11000, stockQuantity: 35, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-lipat-1', productId: 'prod-tilam-lipat-3', imageUrl: '/images/company/aktiviti-pengilangan.jpg', altText: 'Tilam Lipat 3 Berzip Tunas Sinar Jaya', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-tilam-single-asrama',
    name: 'Tilam Single 3 Kaki Asrama & Homestay (Heavy Duty)',
    slug: 'tilam-single-3-kaki-asrama',
    subtitle: 'Pilihan Utama Asrama Sekolah, Pusat Tahfiz & Homestay Bajet',
    description: 'Tilam bujang saiz standard 3 kaki x 6 kaki keluaran Unit Bantal & Tilam Tunas Sinar Jaya. Jahitan tepi tebal dan fabrik berkualiti tinggi yang tahan penggunaan harian lasak. Sesuai untuk asrama sekolah harian, universiti, maahad tahfiz, dan rumah sewa.',
    shortDescription: 'Tilam bujang 3 kaki heavy duty untuk asrama, tahfiz dan homestay. Tahan kemek.',
    categoryId: 'cat-tilam-lipat',
    productType: 'mattress',
    material: 'Rebonded Padat & Asian Polyester Fibre',
    firmness: 'Firm',
    firmnessScale: 7,
    thicknessCm: 10,
    warrantyYears: 2,
    trialNights: 14,
    features: [
      'Ketumpatan tinggi tidak mudah melendut atau kemek',
      'Fabrik jacquard/damask tahan geseran dan lasak',
      'Jahitan tepi piping bertetulang untuk ketahanan bertahun',
      'Saiz tepat untuk katil bujang asrama (Single 3x6 kaki)',
      'Harga kilang untuk belian individu mahupun pukal',
    ],
    layers: [
      { number: 1, name: 'Fabrik Luar Tahan Lasak', description: 'Kain tebal kalis geseran jahitan kilang.' },
      { number: 2, name: 'Lapisan Pelapik Fiber', description: 'Kusyen empuk di bahagian atas dan bawah.' },
      { number: 3, name: 'Teras Padat Rebonded / Fiber', description: 'Teras sokongan teguh untuk ketahanan jangka panjang.' },
    ],
    specifications: {
      'Saiz': 'Single Standard (90cm x 190cm)',
      'Tinggi / Ketebalan': '4 Inci atau 5 Inci',
      'Sesuai Untuk': 'Asrama, Homestay, Bilik Pekerja, Pusat Tahfiz',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [
      { question: 'Bolehkah beli dalam kuantiti banyak untuk asrama?', answer: 'Boleh, sila hubungi kami terus melalui WhatsApp 011-6444 7908 untuk sebut harga pukal dan jadual penghantaran lori kilang.' },
    ],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-asrama-4in', productId: 'prod-tilam-single-asrama', sku: 'TSJ-ASRAMA-4IN', sizeName: 'Single 4 Inci Standard', dimensions: '90cm x 190cm x 10cm', priceSen: 9900, compareAtPriceSen: 13000, stockQuantity: 50, leadTimeDays: 2, isActive: true },
      { id: 'var-asrama-5in', productId: 'prod-tilam-single-asrama', sku: 'TSJ-ASRAMA-5IN', sizeName: 'Single 5 Inci Extra Padat', dimensions: '90cm x 190cm x 13cm', priceSen: 12900, compareAtPriceSen: 16900, stockQuantity: 40, leadTimeDays: 2, isActive: true },
    ],
    images: [
      { id: 'img-asrama-1', productId: 'prod-tilam-single-asrama', imageUrl: '/images/company/aktiviti-pengilangan.jpg', altText: 'Tilam Single Asrama Tunas Sinar Jaya', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-bantal-gebu-asian',
    name: 'Bantal Tidur Gebu Asian Polyester Fibre',
    slug: 'bantal-tidur-gebu-asian-fibre',
    subtitle: 'Isian Fiber Anjal & Sejuk • Sokongan Leher Maksimum',
    description: 'Bantal tidur empuk dan anjal diisi terus di Unit Bantal & Tilam kilang kami. Menggunakan Asian Polyester Fibre bermutu tinggi yang gebu, tidak mudah berketul, dan memberikan sokongan leher yang selesa untuk tidur yang lena.',
    shortDescription: 'Bantal tidur gebu berkualiti tinggi dari Unit Bantal & Tilam KAMAAR. Lembut dan anjal.',
    categoryId: 'cat-bantal',
    productType: 'pillow',
    material: '100% Asian Polyester Virgin Fibre',
    firmness: 'Medium Soft',
    firmnessScale: 4,
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Isian Asian Polyester Virgin Fibre gred A yang gebu & anjal',
      'Kain sarung kapas mikrofiber yang sejuk dan lembut',
      'Boleh dibasuh dan cepat kering',
      'Hypoallergenic dan bebas habuk fabrik',
      'Harga jimat terus dari kilang',
    ],
    layers: [],
    specifications: {
      'Saiz Bantal': 'Standard (48cm x 74cm)',
      'Berat': 'Kira-kira 850g (Padat & Gebu)',
      'Bahan Isian': 'Asian Polyester Fibre',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [
      { question: 'Bolehkah bantal ini dibasuh?', answer: 'Ya, bantal ini boleh dicuci secara cucian lembut dalam mesin basuh dan dijemur kering di bawah matahari.' },
    ],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-bantal-1pc', productId: 'prod-bantal-gebu-asian', sku: 'TSJ-BANTAL-1PC', sizeName: '1 Biji Bantal Standard', dimensions: '48cm x 74cm', priceSen: 1800, compareAtPriceSen: 2500, stockQuantity: 150, leadTimeDays: 1, isActive: true },
      { id: 'var-bantal-2pc', productId: 'prod-bantal-gebu-asian', sku: 'TSJ-BANTAL-2PC', sizeName: 'Pakej Kombo 2 Biji', dimensions: '48cm x 74cm', priceSen: 3200, compareAtPriceSen: 5000, stockQuantity: 100, leadTimeDays: 1, isActive: true },
      { id: 'var-bantal-4pc', productId: 'prod-bantal-gebu-asian', sku: 'TSJ-BANTAL-4PC', sizeName: 'Pakej Keluarga 4 Biji (Jimat)', dimensions: '48cm x 74cm', priceSen: 5900, compareAtPriceSen: 10000, stockQuantity: 80, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-bantal-1', productId: 'prod-bantal-gebu-asian', imageUrl: '/images/products/pillow-classic-latex.jpg', altText: 'Bantal Tidur Gebu Asian Polyester Fibre', displayOrder: 1, isPrimary: true },
      { id: 'img-bantal-2', productId: 'prod-bantal-gebu-asian', imageUrl: '/images/company/aktiviti-pengilangan.jpg', altText: 'Unit Bantal & Tilam Tunas Sinar Jaya', displayOrder: 2, isPrimary: false },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-bantal-peluk-gebu',
    name: 'Bantal Peluk (Bolster) Gebu Jahitan Kemas',
    slug: 'bantal-peluk-bolster-gebu',
    subtitle: 'Panjang & Gemuk • Isian Padat Tidak Mudah Leper',
    description: 'Bantal peluk panjang dengan isian fiber padat gebu. Jahitan kemas dan fabrik lembut yang memberikan pelukan empuk setiap malam untuk tidur yang lebih selesa.',
    shortDescription: 'Bantal peluk gebu panjang keluaran kilang KAMAAR. Isian padat dan sedap dipeluk.',
    categoryId: 'cat-bantal',
    productType: 'pillow',
    material: 'Asian Polyester Fibre Padat',
    firmness: 'Medium Soft',
    firmnessScale: 4,
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Isian padat dan tidak mudah penyek bila dipeluk',
      'Jahitan piping keliling yang kukuh',
      'Saiz panjang standard muat semua sarung bantal peluk pasaran',
    ],
    layers: [],
    specifications: {
      'Saiz': 'Standard Dewasa (22cm x 92cm)',
      'Berat': 'Kira-kira 950g',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-peluk-1pc', productId: 'prod-bantal-peluk-gebu', sku: 'TSJ-PELUK-1PC', sizeName: '1 Unit Bantal Peluk', dimensions: '22cm x 92cm', priceSen: 2400, compareAtPriceSen: 3500, stockQuantity: 80, leadTimeDays: 1, isActive: true },
      { id: 'var-peluk-2pc', productId: 'prod-bantal-peluk-gebu', sku: 'TSJ-PELUK-2PC', sizeName: 'Kombo 2 Unit Bantal Peluk', dimensions: '22cm x 92cm', priceSen: 4500, compareAtPriceSen: 7000, stockQuantity: 50, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-peluk-1', productId: 'prod-bantal-peluk-gebu', imageUrl: '/images/company/aktiviti-pengilangan.jpg', altText: 'Bantal Peluk Gebu Tunas Sinar Jaya', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-comforter-tebal-quilting',
    name: 'Set Comforter Tebal Quilting Corak Menarik',
    slug: 'set-comforter-tebal-quilting',
    subtitle: 'Jahitan Quilting Kilang Sendiri • Lembut & Sejuk Dipakai',
    description: 'Comforter tebal dijahit dengan mesin quilting khas Unit Jahitan Tunas Sinar Jaya. Fabrik mikrofiber sejuk dengan isian fiber lembut dan kemas. Pilihan pelbagai corak menarik untuk menceriakan bilik tidur anda.',
    shortDescription: 'Set comforter tebal jahitan quilting kilang sendiri. Lembut, sejuk dan tahan basuh.',
    categoryId: 'cat-cadang-comforter',
    productType: 'bedding',
    material: 'Mikrofiber Sejuk & Isian Fiber Quilting',
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Jahitan quilting kemas mengelakkan fiber bergumpal',
      'Kain sejuk lembut, tidak berbulu selepas dibasuh',
      'Pakej lengkap comforter tebal bersama 2 sarung bantal',
    ],
    layers: [],
    specifications: {
      'Kandungan Set': '1 Comforter Tebal + 2 Sarung Bantal',
      'Material': 'Mikrofiber Lembut Berquilting',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-comf-queen', productId: 'prod-comforter-tebal-quilting', sku: 'TSJ-COMF-QEN', sizeName: 'Queen (200cm x 230cm)', dimensions: '200cm x 230cm', priceSen: 7900, compareAtPriceSen: 11000, stockQuantity: 40, leadTimeDays: 1, isActive: true },
      { id: 'var-comf-king', productId: 'prod-comforter-tebal-quilting', sku: 'TSJ-COMF-KNG', sizeName: 'King (220cm x 240cm)', dimensions: '220cm x 240cm', priceSen: 9900, compareAtPriceSen: 13900, stockQuantity: 30, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-comf-1', productId: 'prod-comforter-tebal-quilting', imageUrl: '/images/company/profil-syarikat-cover.jpg', altText: 'Set Comforter Quilting KAMAAR', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-sarung-toto-berzip',
    name: 'Cadar & Sarung Tilam Toto Berzip Pelbagai Corak',
    slug: 'cadar-sarung-tilam-toto-berzip',
    subtitle: 'Zip Penuh Tahan Karat • Kain Sejuk Tidak Luntur',
    description: 'Sarung gantian berzip penuh untuk tilam toto anda. Senang dibuka untuk dibasuh, kain tebal tidak mudah koyak dan corak tidak luntur.',
    shortDescription: 'Sarung ganti berzip penuh untuk tilam toto. Senang buka basuh dan kain berkualiti.',
    categoryId: 'cat-cadang-comforter',
    productType: 'bedding',
    material: 'Kapas Mikrofiber Sejuk Berzip',
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Zip panjang memudahkan proses memasukkan dan mengeluarkan tilam toto',
      'Kain sejuk lembut yang selesa bila berbaring',
      'Corak moden dan floral bunga ceria',
    ],
    layers: [],
    specifications: {
      'Jenis': 'Sarung Berzip Tilam Toto',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise',
    },
    faq: [],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-sarung-sgl', productId: 'prod-sarung-toto-berzip', sku: 'TSJ-SRG-SGL', sizeName: 'Single (90x190cm)', dimensions: '90cm x 190cm', priceSen: 2500, compareAtPriceSen: 3500, stockQuantity: 60, leadTimeDays: 1, isActive: true },
      { id: 'var-sarung-qen', productId: 'prod-sarung-toto-berzip', sku: 'TSJ-SRG-QEN', sizeName: 'Queen (150x190cm)', dimensions: '150cm x 190cm', priceSen: 3500, compareAtPriceSen: 4500, stockQuantity: 70, leadTimeDays: 1, isActive: true },
      { id: 'var-sarung-kng', productId: 'prod-sarung-toto-berzip', sku: 'TSJ-SRG-KNG', sizeName: 'King (180x190cm)', dimensions: '180cm x 190cm', priceSen: 4200, compareAtPriceSen: 5500, stockQuantity: 50, leadTimeDays: 1, isActive: true },
    ],
    images: [
      { id: 'img-sarung-1', productId: 'prod-sarung-toto-berzip', imageUrl: '/images/company/profil-syarikat-cover.jpg', altText: 'Sarung Tilam Toto Berzip KAMAAR', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
  {
    id: 'prod-pakej-borong-10set',
    name: 'Pakej Tempahan Pukal Asrama & Homestay (Jualan Gudang)',
    slug: 'pakej-pukal-asrama-homestay',
    subtitle: 'Harga Borong Terus Kilang • Termasuk Tilam + Bantal Gebu',
    description: 'Pakej jualan gudang paling jimat untuk pengusaha asrama sekolah, tahfiz, homestay, atau kem latihan. Jimat sehingga ratusan ringgit bila membeli terus dari kilang pengeluar Tunas Sinar Jaya di Tasek Gelugor.',
    shortDescription: 'Pakej borong jualan gudang terus dari kilang untuk homestay dan asrama.',
    categoryId: 'cat-borong-gudang',
    productType: 'mattress',
    material: 'Tilam & Bantal Lengkap Terus Kilang',
    warrantyYears: 1,
    trialNights: 14,
    features: [
      'Harga borong jimat gila terus dari kilang',
      'Termasuk pakej tilam bujang/toto dan bantal tidur gebu',
      'Boleh runding penghantaran lori terus ke lokasi anda',
      'Sokongan invois rasmi syarikat untuk tuntutan pentadbiran',
    ],
    layers: [],
    specifications: {
      'Pakej': '10 Set Lengkap (10 Tilam + 10 Bantal Gebu)',
      'Pengeluar': 'Tunas Sinar Jaya Enterprise (Tasek Gelugor)',
      'Pesanan Khas': 'WhatsApp 011-6444 7908',
    },
    faq: [],
    status: 'published',
    isFeatured: true,
    variants: [
      { id: 'var-borong-10set', productId: 'prod-pakej-borong-10set', sku: 'TSJ-BORONG-10', sizeName: 'Pakej 10 Set Lengkap', dimensions: '10 Tilam + 10 Bantal', priceSen: 65000, compareAtPriceSen: 85000, stockQuantity: 20, leadTimeDays: 3, isActive: true },
      { id: 'var-borong-20set', productId: 'prod-pakej-borong-10set', sku: 'TSJ-BORONG-20', sizeName: 'Pakej 20 Set Lengkap (Super Jimat)', dimensions: '20 Tilam + 20 Bantal', priceSen: 120000, compareAtPriceSen: 170000, stockQuantity: 10, leadTimeDays: 3, isActive: true },
    ],
    images: [
      { id: 'img-borong-1', productId: 'prod-pakej-borong-10set', imageUrl: '/images/company/misi-visi-jualan-gudang.jpg', altText: 'Jualan Gudang Tekstil Tunas Sinar Jaya', displayOrder: 1, isPrimary: true },
    ],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-10-07T00:00:00Z',
  },
];

const initialCoupons = [
  {
    id: 'coup-kamaar5',
    code: 'KAMAAR5',
    description: 'Baucar diskaun RM5 untuk pembelian tilam toto & bantal',
    discountType: 'fixed_amount',
    discountValue: 500, // RM5.00
    minSpendSen: 5000,
    usageLimit: 1000,
    usageCount: 15,
    perCustomerLimit: 2,
    startsAt: '2026-01-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
    isActive: true,
    showOnHomepage: true,
    featuredOrder: 1,
    customTitle: 'Diskaun Pelanggan Baharu RM5',
    customBadge: 'RM5 OFF',
    customerRestriction: 'all',
    applicableCategory: 'all',
  },
  {
    id: 'coup-kamaar10',
    code: 'KAMAAR10',
    description: 'Potongan RM10 untuk pesanan melebihi RM100',
    discountType: 'fixed_amount',
    discountValue: 1000, // RM10.00
    minSpendSen: 10000,
    usageLimit: 500,
    usageCount: 22,
    perCustomerLimit: 1,
    startsAt: '2026-01-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
    isActive: true,
    showOnHomepage: true,
    featuredOrder: 2,
    customTitle: 'Baucar Istimewa RM10',
    customBadge: 'RM10 OFF',
    customerRestriction: 'all',
    applicableCategory: 'all',
  },
  {
    id: 'coup-borong50',
    code: 'BORONGVIP',
    description: 'Diskaun borong khas RM50 untuk tempahan melebihi RM500',
    discountType: 'fixed_amount',
    discountValue: 5000, // RM50.00
    minSpendSen: 50000,
    usageLimit: 200,
    usageCount: 8,
    perCustomerLimit: 1,
    startsAt: '2026-01-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
    isActive: true,
    showOnHomepage: true,
    featuredOrder: 3,
    customTitle: 'Diskaun Borong Kilang RM50',
    customBadge: 'RM50 OFF',
    customerRestriction: 'all',
    applicableCategory: 'all',
  },
  {
    id: 'coup-freeship',
    code: 'FREESHIP',
    description: 'Penghantaran Percuma Semenanjung Malaysia',
    discountType: 'free_shipping',
    discountValue: 0,
    minSpendSen: 0,
    usageLimit: 1000,
    usageCount: 45,
    perCustomerLimit: 3,
    startsAt: '2026-01-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
    isActive: true,
    showOnHomepage: true,
    featuredOrder: 4,
    customTitle: 'Penghantaran Percuma',
    customBadge: 'FREE POSTAGE',
    customerRestriction: 'all',
    applicableCategory: 'all',
  },
];

const initialShowrooms = [
  {
    id: 'sr-tasek-gelugor',
    name: 'Kilang & Stor Jualan Gudang Utama Tunas Sinar Jaya',
    address: '7878B Jalan Permatang Berangan',
    city: 'Tasek Gelugor',
    state: 'Pulau Pinang',
    postcode: '13300',
    phone: '011-6444 7908',
    openingHours: 'Isnin - Sabtu: 9:00 AM - 6:00 PM (Ahad: Temujanji Jualan Gudang)',
    mapUrl: 'https://maps.google.com/?q=7878B+Jalan+Permatang+Berangan+13300+Tasek+Gelugor+Pulau+Pinang',
    imageUrl: '/images/company/carta-organisasi-kilang.jpg',
    displayOrder: 1,
    isActive: true,
  },
];

const initialBlogPosts = [
  {
    id: 'blog-1',
    slug: 'panduan-penjagaan-tilam-toto-dan-bantal-fiber',
    title: 'Panduan Penjagaan Tilam Toto & Bantal Fiber Agar Kekal Gebu',
    excerpt: 'Petua mudah daripada tukang jahit kilang kami untuk mengekalkan keempukan dan kebersihan tilam toto seisi keluarga.',
    content: 'Tilam toto Asian Polyester Fibre keluaran Tunas Sinar Jaya direka untuk ketahanan maksimum. Untuk memastikan ia sentiasa empuk dan bersih:\n1. Jemur di bawah cahaya matahari pagi setiap 2 minggu untuk mematikan hama dan mengembalikan kegebuan fiber.\n2. Gunakan sarung berzip gantian untuk memudahkan cucian sarung luar.\n3. Elakkan melipat tilam toto secara kasar; lebih baik digulung secara kemas bagi menjaga struktur jahitan quilting.',
    author: 'Tunas Sinar Jaya Enterprise',
    imageUrl: '/images/company/profil-syarikat-cover.jpg',
    tags: ['Panduan', 'Tilam Toto', 'Tips'],
    publishedAt: '2026-09-15T09:00:00Z',
    isPublished: true,
  },
  {
    id: 'blog-2',
    slug: 'kenapa-tilam-lipat-3-pilihan-terbaik-asrama-homestay',
    title: 'Kelebihan Tilam Lipat 3 Berzip Untuk Asrama & Homestay',
    excerpt: 'Mengapa pengusaha homestay dan warden asrama lebih gemar memilih tilam lipat berbanding tilam span biasa.',
    content: 'Tilam lipat 3 bahagian memberikan fleksibiliti tinggi kepada pemilik homestay dan asrama. Bila tidak digunakan, ia boleh dilipat dan disusun rapi, menjimatkan ruang bilik. Tambahan pula, dengan sarung berzip, kebersihan tilam lebih terjamin kerana sarung boleh dicuci mesin.',
    author: 'Hazizi Md Rashid (Pengurus Operasi)',
    imageUrl: '/images/company/aktiviti-pengilangan.jpg',
    tags: ['Asrama', 'Homestay', 'Tilam Lipat'],
    publishedAt: '2026-09-20T10:00:00Z',
    isPublished: true,
  },
  {
    id: 'blog-3',
    slug: 'profil-pengilang-tekstil-bumiputera-tasek-gelugor',
    title: 'Menjahit Kepercayaan, Menyulam Masa Depan di Tasek Gelugor',
    excerpt: 'Perjalanan Tunas Sinar Jaya Enterprise dalam menghasilkan produk jahitan tekstil berkualiti tinggi dengan harga berpatutan.',
    content: 'Bermula dari bengkel jahitan tempatan, Tunas Sinar Jaya Enterprise kini berkembang dengan unit pengeluaran yang sistematik merangkumi Unit Potong Kain, Unit Jahitan, Unit Bantal & Tilam, serta Stor Produk Siap. Komitmen kami adalah menghasilkan produk tekstil Bumiputera yang berkualiti tinggi dan berpatutan untuk seluruh rakyat Malaysia.',
    author: 'Hezwan Md Rashid (Bahagian Pentadbiran)',
    imageUrl: '/images/company/carta-organisasi-kilang.jpg',
    tags: ['Profil Syarikat', 'Tasek Gelugor', 'Tekstil'],
    publishedAt: '2026-09-25T11:00:00Z',
    isPublished: true,
  },
];

const initialSiteSettings = {
  brandName: 'KAMAAR Beddings',
  logoText: 'TUNAS SINAR JAYA ENTERPRISE (KAMAAR BEDDINGS)',
  tagline: 'Kualiti Jahitan, Kepuasan Terjamin • Menjahit Kepercayaan, Menyulam Masa Depan',
  currency: 'MYR',
  currencySymbol: 'RM',
  contactEmail: 'tunassinar@gmail.com',
  contactPhone: '011-6444 7908',
  whatsappNumber: '+601164447908',
  address: '7878B Jalan Permatang Berangan, 13300 Tasek Gelugor SPU, Pulau Pinang',
  announcementText: 'Jualan Gudang Terus Dari Kilang • Penghantaran ke Seluruh Semenanjung Malaysia',
  announcementUrl: '/collections/tilam-toto',
  isAnnouncementActive: true,
  announcementActive: true,
  freeShippingThresholdSen: 20000,
  peninsularShippingSen: 1500,
  eastMalaysiaShippingSen: 4500,
  warrantyDefaultYears: 1,
  trialDefaultNights: 14,
};

const initialStaffMembers = [
  {
    id: 'staff-hazizi',
    email: 'hazizi@kamaar.my',
    name: 'Hazizi Md Rashid',
    role: 'owner',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'staff-hezwan',
    email: 'hezwan@kamaar.my',
    name: 'Hezwan Md Rashid',
    role: 'owner',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'staff-elias',
    email: 'elias@kamaar.my',
    name: 'Elias Mat Rashid',
    role: 'catalog_manager',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'staff-chejam',
    email: 'chejam@kamaar.my',
    name: 'Che Jam Darus',
    role: 'order_manager',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'staff-yahya',
    email: 'yahya@kamaar.my',
    name: 'Yahya Bin Ishak',
    role: 'content_editor',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'staff-zuki',
    email: 'zuki@kamaar.my',
    name: 'Zuki Musa',
    role: 'order_manager',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
  },
];

const initialReviews = [
  {
    id: 'rev-1',
    productId: 'prod-toto-asian-fibre',
    customerName: 'Kak Siti Noraini (Bertam, Kepala Batas)',
    rating: 5,
    title: 'Tilam toto sangat gebu dan tebal!',
    content: 'Beli saiz Queen corak bunga biru. Memang tebal betul, anak-anak suka baring depan TV. Jahitan quilting kemas sangat, tak rugi beli terus dari kilang Tasek Gelugor.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-toto-asian-fibre',
    customerName: 'En. Azman (Pengusaha Homestay Butterworth)',
    rating: 5,
    title: 'Pilihan terbaik untuk homestay!',
    content: 'Saya order 5 set tilam toto untuk homestay saya. Tetamu puji selesa bila tidur. Harga memang berpatutan berbanding kedai luar. Servis Tunas Sinar Jaya sangat mesra.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-15T11:20:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-tilam-lipat-3',
    customerName: 'Adib Danial (Pelajar USM Pulau Pinang)',
    rating: 5,
    title: 'Senang lipat dan jimat ruang bilik sewa',
    content: 'Beli tilam lipat 3 inci tebal. Memang sedap baring dan sarung berzip senang dibuka bila nak cuci. Penghantaran pun laju.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-20T16:45:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-bantal-gebu-asian',
    customerName: 'Puan Halimah (Sungai Petani, Kedah)',
    rating: 5,
    title: 'Bantal empuk tak sakit leher',
    content: 'Order pakej kombo 4 biji bantal gebu. Sangat puas hati! Fiber penuh tapi tak keras. Bangun pagi rasa segar.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-24T09:10:00Z',
  },
];

const initialAffiliates = [
  {
    id: 'aff-danial',
    code: 'AFF-DANIAL',
    name: 'Ahmad Danial',
    email: 'danial@kamaar.my',
    phone: '011-6444 7908',
    bankName: 'Maybank',
    bankAccountNumber: '164012345678',
    commissionType: 'percentage',
    commissionRate: 10,
    totalSalesCount: 15,
    totalSalesRevenueSen: 125000,
    totalCommissionSen: 12500,
    isActive: true,
    createdAt: '2026-08-01T10:00:00Z',
    adminNotes: 'Ejen aktif kawasan Seberang Perai & Kedah.',
    accessKey: 'kamaar123',
  },
];

const initialWebsiteConfig = {
  theme: {
    primaryColor: '#1E4E8C',
    primaryDarkColor: '#13325B',
    accentGoldColor: '#B49A58',
    backgroundColor: '#FFFFFF',
    creamColor: '#F4F7FB',
    textColor: '#0F172A',
    saleColor: '#A13D40',
  },
  announcement: {
    enabled: true,
    leftBenefit: 'Penghantaran Terus Semenanjung',
    centerText: 'Jualan Gudang Terus Dari Kilang • Gunakan Kod',
    highlightCode: 'KAMAAR10',
    url: '/collections/tilam-toto',
    rightGuarantee: 'Kualiti Jahitan Terjamin',
    bgColor: '#13325B',
    textColor: '#FFFFFF',
  },
  megaMenu: {
    enabled: true,
    columns: [],
    promoCard: {
      enabled: true,
      badge: 'PALING LARISS',
      title: 'Tilam Toto Kilang',
      description: 'Asian Polyester Fibre tebal & empuk terus dari kilang Tasek Gelugor.',
      buttonText: 'Beli Sekarang',
      buttonUrl: '/collections/tilam-toto',
    },
  },
  hero: {
    slides: [
      {
        id: 'slide-1',
        badge: 'PALING LARISS!!',
        title: 'Tilam Toto Asian Polyester Fibre Gebu & Tebal',
        subtitle: 'Mengilang dan memasar produk jahitan tekstil berkualiti tinggi terus dari kilang Tasek Gelugor. Keselesaan anda keutamaan kami.',
        ctaText: 'Beli Tilam Toto Sekarang',
        ctaLink: '/collections/tilam-toto',
        secondaryCtaText: 'Lihat Profil Syarikat',
        secondaryCtaLink: '/profil',
        imageUrl: '/images/company/profil-syarikat-cover.jpg',
        isActive: true,
      },
      {
        id: 'slide-2',
        badge: 'PENGILANG BUMIPUTERA',
        title: 'Kualiti Jahitan, Kepuasan Pelanggan Terjamin',
        subtitle: 'Proses pengeluaran sistematik merangkumi Unit Potong Kain, Unit Jahitan, Unit Bantal & Tilam, serta Stor Produk Siap.',
        ctaText: 'Lihat Aktiviti Kilang',
        ctaLink: '/profil',
        secondaryCtaText: 'Hubungi Kami',
        secondaryCtaLink: '/contact',
        imageUrl: '/images/company/aktiviti-pengilangan.jpg',
        isActive: true,
      },
      {
        id: 'slide-3',
        badge: 'HARGA BORONG GUDANG',
        title: 'Jualan Gudang & Tempahan Pukal Asrama / Homestay',
        subtitle: 'Dapatkan harga kilang paling berpatutan untuk tilam bujang asrama, tilam lipat, bantal tidur gebu, dan comforter berkualiti.',
        ctaText: 'Terokai Pakej Borong',
        ctaLink: '/collections/borong-gudang',
        secondaryCtaText: 'WhatsApp 011-6444 7908',
        secondaryCtaLink: 'https://wa.me/601164447908',
        imageUrl: '/images/company/misi-visi-jualan-gudang.jpg',
        isActive: true,
      },
    ],
  },
  reassurance: {
    items: [
      {
        id: 'reassure-1',
        icon: 'sparkles',
        title: 'Kualiti Terjamin',
        subtitle: 'Kawalan mutu ketat, jahitan kemas dan isian Asian Polyester Fibre berkualiti.',
      },
      {
        id: 'reassure-2',
        icon: 'trial',
        title: 'Pengeluaran Cekap',
        subtitle: 'Tenaga kerja mahir dengan fasiliti jahitan dan quilting kilang sendiri.',
      },
      {
        id: 'reassure-3',
        icon: 'shield',
        title: 'Harga Berpatutan',
        subtitle: 'Harga terus dari kilang tanpa orang tengah untuk penjimatan maksimum.',
      },
      {
        id: 'reassure-4',
        icon: 'truck',
        title: 'Komitmen Pelanggan',
        subtitle: 'Penghantaran pantas, perkhidmatan mesra dan jaminan kepuasan pelanggan.',
      },
    ],
  },
  promotionsBanner: {
    enabled: true,
    badge: 'PROMOSI JUALAN GUDANG',
    headline: 'Dapatkan Tilam Toto & Bantal Gebu Terus Dari Kilang',
    description: 'Nikmati harga istimewa dan baucar diskaun KAMAAR10 untuk pesanan dalam talian minggu ini.',
    couponCode: 'KAMAAR10',
    imageUrl: '/images/company/profil-syarikat-cover.jpg',
    ctaText: 'Beli Sekarang',
    ctaLink: '/collections/tilam-toto',
  },
  storySection: {
    badge: 'TUNAS SINAR JAYA ENTERPRISE',
    headline: 'Mengilang & Memasar Produk Jahitan Tekstil Berkualiti',
    paragraph1: 'TUNAS SINAR JAYA ENTERPRISE merupakan sebuah syarikat tempatan yang terlibat dalam pengilangan dan pemasaran produk jahitan tekstil di Tasek Gelugor, Pulau Pinang. Berbekalkan pengalaman, tenaga kerja mahir serta komitmen terhadap kualiti, kami menghasilkan Tilam Toto, tilam lipat, bantal gebu dan cadar pada harga kompetitif.',
    paragraph2: 'Kami memberi penekanan kepada penggunaan bahan berkualiti, proses pengeluaran yang sistematik serta kawalan mutu yang ketat bagi memastikan setiap produk mencapai standard yang tinggi. Moto kami: "Kualiti Jahitan, Kepuasan Terjamin" — Menjahit Kepercayaan, Menyulam Masa Depan.',
    imageUrl: '/images/company/aktiviti-pengilangan.jpg',
    signatureTitle: 'Hazizi Md Rashid',
    signatureSub: 'Pengurus Operasi, Tunas Sinar Jaya Enterprise',
  },
  socialAndContact: {
    whatsappNumber: '+601164447908',
    phoneDisplay: '011-6444 7908',
    emailDisplay: 'tunassinar@gmail.com',
    addressDisplay: '7878B Jalan Permatang Berangan, 13300 Tasek Gelugor SPU, Pulau Pinang',
    instagramUrl: '',
    tiktokUrl: 'https://www.tiktok.com/@kamaar_shop',
    facebookUrl: 'https://www.facebook.com',
  },
  appearance: {
    enableEntranceAnimations: true,
    enableFloatingBadges: true,
    cardBorderRadius: 'rounded-2xl',
  },
};

const initialPaymentSettings = {
  expressCheckoutEnabled: true,
  enableGooglePay: false,
  enableApplePay: false,
  defaultMethodId: 'pay-fpx',
  methods: [
    {
      id: 'pay-fpx',
      name: 'FPX Online Banking',
      subtitle: 'Maybank2u, CIMB Clicks, Public Bank, RHB, Hong Leong & semua bank Malaysia',
      providerType: 'fpx',
      enabled: true,
      isDefault: true,
      testMode: false,
      sortOrder: 1,
      badgeIcons: ['fpx'],
      description: 'Bayar terus melalui perbankan internet rasmi Malaysia (FPX). Selamat, pantas dan disahkan serta-merta.',
      instructions: 'Pilih bank pilihan anda di bawah untuk log masuk ke perbankan internet dan sahkan bayaran.',
    },
    {
      id: 'pay-tng',
      name: 'Touch \'n Go eWallet (TNG)',
      subtitle: 'Imbas kod QR TNG eWallet atau bayar terus melalui aplikasi Touch \'n Go',
      providerType: 'tng',
      enabled: true,
      isDefault: false,
      testMode: false,
      sortOrder: 2,
      badgeIcons: ['tng'],
      description: 'Pembayaran mudah melalui aplikasi Touch \'n Go eWallet terus ke akaun jualan Tunas Sinar Jaya Enterprise.',
      instructions: 'Buka aplikasi TNG eWallet anda dan imbas kod QR rasmi Tunas Sinar Jaya Enterprise / KAMAAR Beddings.',
    },
  ],
};

// Write to lena_db.json
const dbPath = path.join(process.cwd(), 'data', 'lena_db.json');
let existingDb = {};
if (fs.existsSync(dbPath)) {
  try {
    existingDb = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
  } catch (e) {
    existingDb = {};
  }
}

const updatedDb = {
  ...existingDb,
  categories: initialCategories,
  collections: initialCollections,
  products: initialProducts,
  coupons: initialCoupons,
  showrooms: initialShowrooms,
  blogPosts: initialBlogPosts,
  siteSettings: initialSiteSettings,
  staffMembers: initialStaffMembers,
  reviews: initialReviews,
  affiliates: initialAffiliates,
  websiteConfig: initialWebsiteConfig,
  paymentSettings: initialPaymentSettings,
};

fs.writeFileSync(dbPath, JSON.stringify(updatedDb, null, 2), 'utf8');
console.log('Successfully updated data/lena_db.json with Tunas Sinar Jaya Enterprise real data!');
